name: Checkers

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  schedule:
  - cron: '30 12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: JustinBeckwith/linkinator-action@36a0bfbfecd5e237e8f8531537a693616c505faf # v2
      with:
        paths: '*.md'
        timeout: 60000

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: tbroadley/spellchecker-cli-action@8369e98753c0d2c3a3c76fb4519d9056d1d4b129 # v1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md'
